### ISSUE TITLE
(improvement) setting bit field values? 

### ISSUE THREAD

**Issue by nissaba** [ykyouhei/enum_option_set#1]
In the short documentation I have not seen if it was possible to set values to the option like we do in swift optionSets? 

example 

```
struct PowerMeterType: OptionSet {
    let rawValue: UInt8

    static let CTFPowerOffset = PowerMeterType(rawValue: 1 << 0)
    static let CTPWROffset = PowerMeterType(rawValue: 1 << 4)
    static let CTPWRCrankLength = PowerMeterType(rawValue: 1 << 5)
}
```

**Comment by ykyouhei** [comment]
@nissaba 
Thank you for your feedback.

The library implicitly assigns bit values [based on the index of the defined Enums](https://github.com/ykyouhei/enum_option_set/blob/main/lib/src/enum_option_set.dart#L114). Therefore, it is not possible for users to set these values manually.
